language: java
jdk:
  - oraclejdk8
env:
  - TERM=dumb

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/java-sdk/build/libs/*.jar"
  skip_cleanup: true
  on:
    tags: true

before_install:
  - cd java-sdk

after_deploy:
  - ./gradlew bintrayUpload
