#================================ Android Application Monitor =====================================#
name: APPLICATION
app_provider: .application.ApplicationServiceProvider
sensors:
  - name: EXTERNAL_TIME
    sample_rate: 0.08
    unit: NON_DIMENSIONAL
    data_type: RAW
    topic_name: application_external_time
    key_class: .kafka.key.KeyMeasurement
    value_class: .monitor.application.ApplicationExternalTime
  - name: RECORD_COUNTS
    sample_rate: 0.08
    unit: NON_DIMENSIONAL
    data_type: RAW
    topic_name: application_record_counts
    key_class: .kafka.key.KeyMeasurement
    value_class: .monitor.application.ApplicationRecordCounts
  - name: SERVER_STATUS
    sample_rate: 0.08
    unit: NON_DIMENSIONAL
    data_type: RAW
    topic_name: application_server_status
    key_class: .kafka.key.KeyMeasurement
    value_class: .monitor.application.ApplicationServerStatus
  - name: UPTIME
    sample_rate: 0.08
    unit: NON_DIMENSIONAL
    data_type: RAW
    topic_name: application_uptime
    key_class: .kafka.key.KeyMeasurement
    value_class: .monitor.application.ApplicationUptime
